name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-action@main
        with:
          sdk: nightly
          combine: true